[workspace]
authors = ["Neclow <neilclow24@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "bcov3d"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
repro = "dvc repro"
post_install = "bash scripts/post_install.sh"

[tasks.famsa3di]
cmd = "extern/famsa3di/famsa3di"

[dependencies]
# Binary dependencies
dvc = ">=3.63.0,<4"
dvc-ssh = ">=4.2.1,<5"
foldseek = ">=10.941cd33,<11"
pv = ">=1.6.6,<2"
trimal = { version = ">=1.5.0,<2", channel = "bioconda" }
mafft = { version = ">=7.525,<8", channel = "bioconda" }
iqtree = { version = ">=3.0.1,<4", channel = "bioconda" }
# Python dependencies
ipykernel = ">=6.30.1,<7"
ipywidgets = ">=8.1.7,<9"
pandas = ">=2.3.2,<3"
rpy2 = ">=3.6.2,<4"
tqdm = ">=4.67.1,<5"
biopython = ">=1.85,<2"
biotite = ">=1.4.0,<2"
ete4 = ">=4.3.0,<5"
matplotlib = ">=3.10.6,<4"
seaborn = ">=0.13.2,<0.14"
# R dependencies
r-phangorn = ">=2.12.1,<3"
r-ggsci = ">=3.2.0,<4"
r-phytools = ">=2.4_4,<3"
r-tidybayes = ">=3.0.7,<4"
r-cairo = ">=1.6_5,<2"
r-treedist = ">=2.10.1,<3"
r-patchwork = ">=1.3.2,<2"
r-ggnewscale = ">=0.5.2,<0.6"
r-bh = ">=1.87.0_1,<2"
r-ggplot2 = "<4.0.0"
